### PR TITLE
Possibility to passthrough command-line options for gnome-terminal

### PR DESCRIPTION
**Pull request by synaptiko**
Solution for #8... What do you think? Is it ok?

I don't know python so much, maybe it's possible to write it differently. I'm ok to rewrite it.

### CODE REVIEW

**Comment by fmoralesc** [comment]
Seems fine ;) You'll have to run mksrcinfo to update the .SRCINFO file too, though.

**Comment by fmoralesc** [comment]
Still looking nice, still missing the .SRCINFO update ;) Or are you planning on adding more to this PR?

**Comment by synaptiko** [comment]
Didn't know about .SRCINFO and pkgbuild-introspection package until now :-) Updated...

No, I think that's all which is required... But I'm not still able to figure out how to configure gnome-terminal to correctly load my ~/.bashrc... Do you have any hint?

**Comment by fmoralesc** [comment]
You would have to point gnome-terminal to run your shell and inside it, nvim. But that isn't a change I would like to introduce to the wrapper, because of possible differences in user setups.

Instead, I would recommend you add something to your vimrc that could set up the environment values within nvim's execution context. Besides the idea, I'm not sure how that would look.

**Comment by synaptiko** [comment]
Ok, thanks, I'll give it a try and will see... I think I can close it now because all required pieces are there.

**Comment by fmoralesc** [comment]
Let me merge this first lol ;)

**Comment by synaptiko** [comment]
Oh, sorry :-) :+1:

**Comment by fmoralesc** [comment]
Thanks for the PR btw.

**Pull request merged**
